<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; color: #1a1a1a; }
  .header { text-align: center; border-bottom: 2px solid #f97316; padding-bottom: 16px; margin-bottom: 24px; }
  .institution { font-size: 14px; font-weight: bold; color: #f97316; }
  .title { font-size: 20px; font-weight: bold; margin: 8px 0; }
  .field { margin-bottom: 10px; }
  .label { color: #666; font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; }
  .value { font-size: 13px; font-weight: bold; }
  .signature-line { border-top: 1px solid #333; width: 200px; margin-top: 48px; padding-top: 6px; text-align: center; }
  .footer { margin-top: 40px; font-size: 10px; color: #999; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <div class="institution">College of Computing Studies · CCS ProFile</div>
    <div class="title">Medical Certificate</div>
    <div>Official Health & Wellness Repository</div>
  </div>

  <div class="field">
    <div class="label">Student name</div>
    <div class="value">{{ $student->user->name }}</div>
  </div>
  <div class="field">
    <div class="label">Student ID</div>
    <div class="value">{{ $student->student_id }}</div>
  </div>
  <div class="field">
    <div class="label">Certificate type</div>
    <div class="value">{{ ucwords(str_replace('_', ' ', $cert->certificate_type)) }}</div>
  </div>
  <div class="field">
    <div class="label">Condition period</div>
    <div class="value">{{ $cert->condition_start->format('F j, Y') }} – {{ $cert->condition_end->format('F j, Y') }}</div>
  </div>
  <div class="field">
    <div class="label">Issued date</div>
    <div class="value">{{ $cert->issued_date->format('F j, Y') }}</div>
  </div>
  @if($record->notes)
  <div class="field">
    <div class="label">Notes</div>
    <div class="value">{{ $record->notes }}</div>
  </div>
  @endif

  <div class="signature-line">
    {{ $cert->issued_by }}<br>
    <span style="font-size:10px;color:#666;">Attending Physician / School Nurse</span>
  </div>

  <div class="footer">
    Generated by CCS ProFile · {{ now()->format('F j, Y') }} · This document is electronically issued.
  </div>
</body>
</html>
