<!DOCTYPE html>
<html>
<head>
    <title>Student Profile - {{ $student->first_name }} {{ $student->last_name }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.6; }
        .header { text-align: center; border-bottom: 2px solid #ed8936; padding-bottom: 20px; }
        .section-title { font-size: 18px; font-weight: bold; margin-top: 30px; color: #2d3748; background: #f7fafc; padding: 5px 10px; }
        .info-grid { width: 100%; margin-top: 20px; border-collapse: collapse; }
        .info-grid td { padding: 8px; border: 1px solid #e2e8f0; }
        .label { font-weight: bold; color: #4a5568; width: 30%; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #edf2f7; text-align: left; padding: 10px; border: 1px solid #e2e8f0; font-size: 12px; }
        td { padding: 10px; border: 1px solid #e2e8f0; font-size: 11px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #a0aec0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Student Comprehensive Profile</h1>
        <p>Official School Record | Academic Year {{ $student->school_year }}</p>
    </div>

    <div class="section-title">Personal Information</div>
    <table class="info-grid">
        <tr>
            <td class="label">Full Name</td>
            <td>{{ $student->first_name }} {{ $student->middle_name }} {{ $student->last_name }}</td>
        </tr>
        <tr>
            <td class="label">Student ID</td>
            <td>{{ $student->student_id }}</td>
        </tr>
        <tr>
            <td class="label">Year Level</td>
            <td>{{ $student->year_level }}</td>
        </tr>
        <tr>
            <td class="label">Section</td>
            <td>{{ $student->section?->name ?? 'Unassigned' }}</td>
        </tr>
    </table>

    <div class="section-title">Academic Performance (Grades)</div>
    <table>
        <thead>
            <tr>
                <th>Subject</th>
                <th>Quarter</th>
                <th>Score</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($student->grades as $grade)
            <tr>
                <td>{{ $grade->subject }}</td>
                <td>{{ $grade->quarter }}</td>
                <td>{{ $grade->score }}</td>
                <td>{{ $grade->remarks }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Honors & Achievements</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Title</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach($student->achievements as $achievement)
            <tr>
                <td>{{ $achievement->date_awarded }}</td>
                <td>{{ strtoupper($achievement->category) }}</td>
                <td>{{ $achievement->title }}</td>
                <td>{{ $achievement->description }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Behavioral Monitoring</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Severity</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach($student->behaviorLogs as $log)
            <tr>
                <td>{{ $log->date }}</td>
                <td>{{ strtoupper($log->type) }}</td>
                <td>{{ strtoupper($log->severity) }}</td>
                <td>{{ $log->description }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Health History</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Condition</th>
                <th>Narrative</th>
            </tr>
        </thead>
        <tbody>
            @foreach($student->healthRecords as $record)
            <tr>
                <td>{{ $record->date_recorded }}</td>
                <td>{{ $record->condition }}</td>
                <td>{{ $record->description }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by CCS Profile System on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
